version: '3.4'

services:
  database:
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${ORO_DB_USER}'
      MYSQL_PASSWORD: '${ORO_DB_PASSWORD}'
      MYSQL_DATABASE: '${ORO_DB_NAME}'
    volumes:
      - './mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - './mysql/my.cnf:/etc/mysql/conf.d/oro.cnf:ro'
      - 'mysql-data:/var/lib/mysql:delegated'
    ports:
      - '${COMPOSE_PROJECT_PORT_MYSQL:-3306}:3306'
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
      start_period: 60s
      interval: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local
