version: '3.4'

services:
  database:
    image: '${COMPOSE_PROJECT_MYSQL_IMAGE:-mysql:8.0-oracle}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database
    command: '--federated --default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${COMPOSE_PROJECT_ORO_DB_USER:-application}'
      MYSQL_PASSWORD: '${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      MYSQL_DATABASE: '${COMPOSE_PROJECT_DATABASE_NAME:-application}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mysql/my.cnf:/etc/mysql/conf.d/oro.cnf:ro'
      - 'mysql-data:/var/lib/mysql:delegated'
    ports:
      - '${COMPOSE_PROJECT_MYSQL_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX:-33}06:3306'
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
      start_period: 60s
      interval: 5s
      retries: 15
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  database-cli:
    image: '${COMPOSE_PROJECT_MYSQL_IMAGE:-mysql:8.0-oracle}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database_cli
    command: /bin/true
    labels:
      - 'project.name=${COMPOSE_PROJECT_NAME}'
    environment:
      - 'LANG=C.UTF-8'
      - 'DATABASE_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'DATABASE_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-3306}'
      - 'DATABASE_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'DATABASE_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'DATABASE_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
    networks:
      - 'appnet'
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  mysql-data:
    driver: local
