version: '3.4'

services:
  database:
    image: '${COMPOSE_PROJECT_MYSQL_IMAGE:-mysql:8.0-oracle}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database
    command: '--federated --default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${ORO_DB_USER:-application}'
      MYSQL_PASSWORD: '${ORO_DB_PASSWORD:-application}'
      MYSQL_DATABASE: '${ORO_DB_NAME:-application}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mysql/my.cnf:/etc/mysql/conf.d/oro.cnf:ro'
      - 'mysql-data:/var/lib/mysql:delegated'
    ports:
      - '${COMPOSE_PROJECT_PORT_MYSQL:-3306}:3306'
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
      start_period: 60s
      interval: 5s
      retries: 15

volumes:
  mysql-data:
    driver: local
