version: '3.4'

services:
  database:
    image: '${COMPOSE_PROJECT_PGSQL_IMAGE:-postgres}:${COMPOSE_PROJECT_PGSQL_VERSION:-15.1}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database
    command: postgres -c max_locks_per_transaction=10000 -c shared_buffers=512MB
    shm_size: 512m
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_USER: '${COMPOSE_PROJECT_DATABASE_USER:-application}'
      POSTGRES_PASSWORD: '${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      POSTGRES_DB: '${COMPOSE_PROJECT_DATABASE_NAME:-application}'
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/pgsql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - 'postgresql-data:/var/lib/postgresql/data:delegated'
    ports:
      - '${COMPOSE_PROJECT_PGSQL_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX:-54}32:5432'
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: "pg_isready -U ${COMPOSE_PROJECT_DATABASE_USER:-application}"
      start_period: 60s
      interval: 5s
      retries: 15
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  database-cli:
    image: '${COMPOSE_PROJECT_PGSQL_IMAGE:-postgres}:${COMPOSE_PROJECT_PGSQL_VERSION:-15.1}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database_cli
    command: /bin/true
    labels:
      - 'project.name=${COMPOSE_PROJECT_NAME}'
    environment:
      - 'LANG=C.UTF-8'
      - 'DATABASE_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'DATABASE_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-5432}'
      - 'DATABASE_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'DATABASE_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'DATABASE_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
    networks:
      - 'appnet'
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  postgresql-data:
    driver: local
