version: '3.4'

services:
  mutagen:
    container_name: "${COMPOSE_PROJECT_NAME:-unnamed}_mutagen_${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16}-${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        PHP_VERSION: ${COMPOSE_PROJECT_PHP_VERSION:-8.1}
        NODE_VERSION: ${COMPOSE_PROJECT_NODE_VERSION:-16}
        PHP_USER_NAME: ${COMPOSE_PROJECT_PHP_USER_NAME:-developer}
        PHP_USER_GROUP: ${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}
        PHP_UID: ${COMPOSE_PROJECT_PHP_UID:-1000}
        PHP_GID: ${COMPOSE_PROJECT_PHP_GID:-1000}
        COMPOSER_VERSION: "${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    volumes:
      - 'appcode:/var/www:consistent'
    command: "bash -c 'chmod 0777 /var/www; sleep infinity'"
    working_dir: '/var/www'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    networks:
      - 'appnet'
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  cli:
    depends_on:
      mutagen:
        condition: service_started

volumes:
  appcode:
    driver: local
    driver_opts: {}
