version: '3.4'

services:
  fpm:
    image: "digitalspacestudio/orophp:${PHP_VERSION-8.0}"
    user: root
    volumes:
      - 'orocommerce-fpm-appcode:/var/www'
      - 'orocommerce-fpm-appcache:/var/www/var/cache'
      - 'orocommerce-fpm-npm:/var/www/.npm'
      - 'orocommerce-fpm-composer:/var/www/.composer'
      - 'orocommerce-fpm-vendor:/var/www/vendor'
      - 'orocommerce-fpm-node_modules:/var/www/node_modules'
      - './fpm/php-fpm.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-8.0}/php-fpm.conf:ro'
      - './fpm/php.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-8.0}/php.ini:ro'
      - './fpm/prepend.php:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-8.0}/prepend.php:ro'
      - './fpm/entrypoint.sh:/entrypoint.sh:ro'
      - './fpm/msmtprc:/home/linuxbrew/.msmtprc:ro'
    working_dir: '/var/www'
    command: '/bin/bash /entrypoint.sh'
    networks:
      - 'orocommerce'
    environment:
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_HOME=/var/www/.composer'
      - 'COMPOSER_AUTH=$COMPOSER_AUTH'
    env_file:
      - .env
    networks:
      - 'orocommerce'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"
      start_period: 10s
      interval: 5s

  cli:
    image: "digitalspacestudio/orophp:${PHP_VERSION-8.0}"
    volumes:
      - 'orocommerce-fpm-appcode:/var/www'
      - 'orocommerce-fpm-appcache:/var/www/var/cache'
      - 'orocommerce-fpm-npm:/var/www/.npm'
      - 'orocommerce-fpm-composer:/var/www/.composer'
      - 'orocommerce-fpm-vendor:/var/www/vendor'
      - 'orocommerce-fpm-node_modules:/var/www/node_modules'
      - './fpm/php.ini:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-8.0}/php.ini:ro'
      - './fpm/prepend.php:/home/linuxbrew/.linuxbrew/etc/php/${PHP_VERSION-8.0}/prepend.php:ro'
      - './fpm/msmtprc:/home/linuxbrew/.msmtprc:ro'
    working_dir: '/var/www'
    networks:
      - 'orocommerce'
    environment:
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_HOME=/var/www/.composer'
      - 'COMPOSER_AUTH=$COMPOSER_AUTH'
    env_file:
      - .env
    networks:
      - 'orocommerce'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy

  xhgui:
    image: "xhgui/xhgui:0.18.1"
    volumes:
      - ./xhgui/config:/var/www/xhgui/config
      - ./xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${DOCKER_PORT_XHGUI:-8142}:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 'orocommerce'
    healthcheck:
      test: nc -vz -w 1 localhost 80
      start_period: 10s
      interval: 5s

  mail:
    image: "mailhog/mailhog"
    ports:
      - "${DOCKER_PORT_MAIL_HTTP:-8125}:8025"
    networks:
      - 'orocommerce'
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 5s

  mongodb:
    image: percona/percona-server-mongodb:4.4
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./mongo/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "27017"
    networks:
      - 'orocommerce'
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui
      start_period: 10s
      interval: 5s

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx1024m}'
      discovery.type: 'single-node'
    ports:
      - '9200'
    networks:
      - 'orocommerce'
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9200"
      start_period: 15s
      interval: 5s
      retries: 5


  nginx:
    image: 'crunchgeek/nginx-pagespeed'
    environment:
      NGINX_GEOIP: 'off'
      NGINX_PAGESPEED: 'on'
      NGINX_PAGESPEED_IMG: 'on'
      NGINX_PAGESPEED_JS: 'on'
      NGINX_PAGESPEED_CSS: 'on'
      NGINX_PAGESPEED_STORAGE: 'files'
    depends_on:
      fpm:
        condition: service_healthy
    ports:
      - '${DOCKER_PORT_HTTP:-8000}:80'
    volumes:
      - './www:/var/www:ro'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/pagespeed.conf:/etc/nginx/pagespeed.conf:ro'
    networks:
      - 'orocommerce'
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/80"
      start_period: 10s
      interval: 5s

networks:
  orocommerce:

volumes:
  orocommerce-fpm-appcode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/www"
  orocommerce-fpm-appcache:
    driver: local
  orocommerce-fpm-npm:
    driver: local
  orocommerce-fpm-composer:
    driver: local
  orocommerce-fpm-node_modules:
    driver: local
  orocommerce-fpm-vendor:
    driver: local
