version: '3.4'

services:
  database:
    image: 'busybox'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_database
    command: sleep infinity
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: "sh -c 'exit 0'"
