version: '3.4'

services:
  fpm:
    container_name: "${COMPOSE_PROJECT_NAME:-unnamed}_fpm_${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16}-${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        PHP_VERSION: "${COMPOSE_PROJECT_PHP_VERSION:-8.1}"
        NODE_VERSION: "${COMPOSE_PROJECT_NODE_VERSION:-16}"
        PHP_USER_NAME: "${COMPOSE_PROJECT_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}"
        PHP_UID: "${COMPOSE_PROJECT_PHP_UID:-1000}"
        PHP_GID: "${COMPOSE_PROJECT_PHP_GID:-1000}"
        COMPOSER_VERSION: "${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    user: "${COMPOSE_PROJECT_USER_NAME:-developer}"
    command: php-fpm -R
    volumes:
      - 'appcode:/var/www:consistent'
      - 'home-php:/home/php'
      - 'home-root:/root'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony/msmtprc:/home/php/.msmtprc:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'ORO_DB_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
      - 'ORO_DB_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'ORO_DB_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_FPM:-off}'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
      websocket:
        condition: service_started
      consumer:
        condition: service_started
    restart: always
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"
      start_period: 60s
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  cli:
    container_name: "${COMPOSE_PROJECT_NAME:-unnamed}_cli_${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16}-${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        PHP_VERSION: "${COMPOSE_PROJECT_PHP_VERSION:-8.1}"
        NODE_VERSION: "${COMPOSE_PROJECT_NODE_VERSION:-16}"
        PHP_USER_NAME: "${COMPOSE_PROJECT_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}"
        PHP_UID: "${COMPOSE_PROJECT_PHP_UID:-1000}"
        PHP_GID: "${COMPOSE_PROJECT_PHP_GID:-1000}"
        COMPOSER_VERSION: "${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    user: "${COMPOSE_PROJECT_USER_NAME:-developer}"
    volumes:
      - 'appcode:/var/www:consistent'
      - 'home-php:/home/php'
      - 'home-root:/root'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'ORO_DB_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
      - 'ORO_DB_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'ORO_DB_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_CLI:-off}'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  consumer:
    container_name: "${COMPOSE_PROJECT_NAME:-unnamed}_consumer_${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16}-${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    profiles: ["consumer"]
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        PHP_VERSION: "${COMPOSE_PROJECT_PHP_VERSION:-8.1}"
        NODE_VERSION: "${COMPOSE_PROJECT_NODE_VERSION:-16}"
        PHP_USER_NAME: "${COMPOSE_PROJECT_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}"
        PHP_UID: "${COMPOSE_PROJECT_PHP_UID:-1000}"
        PHP_GID: "${COMPOSE_PROJECT_PHP_GID:-1000}"
        COMPOSER_VERSION: "${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    user: "${COMPOSE_PROJECT_USER_NAME:-developer}"
    command: php bin/console oro:message-queue:consume -vv
    volumes:
      - 'appcode:/var/www:consistent'
      - 'home-php:/home/php'
      - 'home-root:/root'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    restart: always
    environment:
      - 'ORO_DB_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
      - 'ORO_DB_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'ORO_DB_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_CONSUMER:-off}'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  websocket:
    container_name: "${COMPOSE_PROJECT_NAME:-unnamed}_websocket_${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16}-${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        PHP_VERSION: "${COMPOSE_PROJECT_PHP_VERSION:-8.1}"
        NODE_VERSION: "${COMPOSE_PROJECT_NODE_VERSION:-16}"
        PHP_USER_NAME: "${COMPOSE_PROJECT_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${COMPOSE_PROJECT_PHP_USER_GROUP:-developer}"
        PHP_UID: "${COMPOSE_PROJECT_PHP_UID:-1000}"
        PHP_GID: "${COMPOSE_PROJECT_PHP_GID:-1000}"
        COMPOSER_VERSION: "${COMPOSE_PROJECT_COMPOSER_VERSION:-2}"
    user: "${COMPOSE_PROJECT_USER_NAME:-developer}"
    command: php bin/console gos:websocket:server
    volumes:
      - 'appcode:/var/www:consistent'
      - 'home-php:/home/php'
      - 'home-root:/root'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    restart: always
    environment:
      - 'ORO_DB_HOST=${COMPOSE_PROJECT_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${COMPOSE_PROJECT_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${COMPOSE_PROJECT_DATABASE_NAME:-application}'
      - 'ORO_DB_USER=${COMPOSE_PROJECT_DATABASE_USER:-application}'
      - 'ORO_DB_PASSWORD=${COMPOSE_PROJECT_DATABASE_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_WEBSOCKET:-off}'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mail:
    image: "cd2team/mailhog"
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_mail
    ports:
      - "${COMPOSE_PROJECT_MAIL_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX:-80}25:8025"
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 2s

  xhgui:
    image: "xhgui/xhgui:0.18.1"
    profiles: ["profiler"]
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/xhgui/config:/var/www/xhgui/config'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${COMPOSE_PROJECT_XHGUI_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX}81:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: nc -vz -w 1 localhost 80
      start_period: 30s
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mongodb:
    image: percona/percona-server-mongodb:4.4
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_mongodb
    profiles: ["profiler"]
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mongo/initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui
      start_period: 30s
      interval: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  elasticsearch:
    image: '${COMPOSE_PROJECT_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch-oss}:${COMPOSE_PROJECT_ELASTICSEARCH_VERSION:-7.13.2}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_elasticsearch
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data:delegated"
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms256m -Xmx2048m}'
      discovery.type: 'single-node'
    ports:
      - "${COMPOSE_PROJECT_ES_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX:-92}92:9200"
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9200"
      start_period: 60s
      interval: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: ${COMPOSE_PROJECT_NAME:-unnamed}_nginx
    build: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/nginx"
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_nginx
    depends_on:
      fpm:
        condition: service_healthy
    ports:
      - '${COMPOSE_PROJECT_NGINX_BIND_HOST:-127.0.0.1}:${COMPOSE_PROJECT_PORT_PREFIX}80:80'
    volumes:
      - 'appcode:/var/www:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/80"
      start_period: 30s
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  appnet:

volumes:
  appcode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${COMPOSE_PROJECT_APPDIR:-$PWD}"
  home-php:
    driver: local
  home-root:
    driver: local
  elasticsearch-data:
    driver: local
