version: '3.4'

services:
  fpm:
    image: ${COMPOSE_PROJECT_NAME:-unnamed}_php-node:${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_fpm_${COMPOSE_PROJECT_PHP_VERSION:-8.1}_${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php"
      args:
        PHP_VERSION: ${COMPOSE_PROJECT_PHP_VERSION:-8.1}
        NODE_VERSION: ${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    command: php-fpm
    user: root
    volumes:
      - 'appcode:/var/www:consistent'
      - 'npm:/home/developer/.npm'
      - 'composer:/home/developer/.composer'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php/msmtprc:/home/developer/.msmtprc:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
#    entrypoint: '/entrypoint.sh'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    environment:
      - 'ORO_DB_HOST=${ORO_DB_HOST:-database}'
      - 'ORO_DB_PORT=${ORO_DB_PORT:-3306}'
      - 'ORO_DB_NAME=${ORO_DB_NAME:-application}'
      - 'ORO_DB_USER=${ORO_DB_USER:-application}'
      - 'ORO_DB_PASSWORD=${ORO_DB_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-{}}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"
      start_period: 60s
      interval: 5s

  cli:
    image: ${COMPOSE_PROJECT_NAME:-unnamed}_php-node:${COMPOSE_PROJECT_PHP_VERSION:-8.1}-${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_cli_${COMPOSE_PROJECT_PHP_VERSION:-8.1}_${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    build:
      context: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php"
      args:
        PHP_VERSION: ${COMPOSE_PROJECT_PHP_VERSION:-8.1}
        NODE_VERSION: ${COMPOSE_PROJECT_NODE_VERSION:-16.16.0}
    user: root
    volumes:
      - 'appcode:/var/www:consistent'
      - 'npm:/home/developer/.npm'
      - 'composer:/home/developer/.composer'
#      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/cli/php.ini:/home/developer/.developer/etc/php/${COMPOSE_PROJECT_PHP_VERSION-8.0}/php.ini.dist:ro'
#      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/fpm/msmtprc:/home/developer/.msmtprc:ro'
#      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/cli/entrypoint.sh:/entrypoint.sh:ro'
#    entrypoint: '/entrypoint.sh'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro'
    working_dir: '/var/www'
    networks:
      - 'appnet'
    environment:
      - 'ORO_DB_HOST=${ORO_DB_HOST:-database}'
      - 'ORO_DB_PORT=${ORO_DB_PORT:-3306}'
      - 'ORO_DB_NAME=${ORO_DB_NAME:-application}'
      - 'ORO_DB_USER=${ORO_DB_USER:-application}'
      - 'ORO_DB_PASSWORD=${ORO_DB_PASSWORD:-application}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${COMPOSE_PROJECT_COMPOSER_AUTH:-{}}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mail:
        condition: service_healthy

  mail:
    image: "mailhog/mailhog"
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_mail
    ports:
      - "${COMPOSE_PROJECT_PORT_PREFIX:-301}25:8025"
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 5s

  xhgui:
    image: "xhgui/xhgui:0.18.1"
    profiles: ["profiler"]
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/xhgui/config:/var/www/xhgui/config'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${COMPOSE_PROJECT_PORT_PREFIX:-301}81:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: nc -vz -w 1 localhost 80
      start_period: 30s
      interval: 5s

  mongodb:
    image: percona/percona-server-mongodb:4.4
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_mongodb
    profiles: ["profiler"]
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/mongo/initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui
      start_period: 30s
      interval: 10s

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:${COMPOSE_PROJECT_ELASTICSEARCH_VERSION-7.10.2}'
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_elasticsearch
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data:delegated"
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms256m -Xmx2048m}'
      discovery.type: 'single-node'
    ports:
      - "${COMPOSE_PROJECT_PORT_PREFIX:-301}92:9200"
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9200"
      start_period: 60s
      interval: 5s
      retries: 5

  nginx:
    image: ${COMPOSE_PROJECT_NAME:-unnamed}_nginx
    build: "${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/nginx"
    container_name: ${COMPOSE_PROJECT_NAME:-unnamed}_nginx
    depends_on:
      fpm:
        condition: service_healthy
    ports:
      - '${COMPOSE_PROJECT_PORT_PREFIX:-301}80:80'
    volumes:
      - 'appcode:/var/www:ro'
      - '${COMPOSE_PROJECT_CONFIG_DIR:-.}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    networks:
      - 'appnet'
    restart: on-failure:3
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/80"
      start_period: 30s
      interval: 5s

networks:
  appnet:

volumes:
  appcode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${COMPOSE_PROJECT_APPDIR:-$PWD}"
  npm:
    driver: local
  composer:
    driver: local
  elasticsearch-data:
    driver: local
